services:
  - type: web
    name: wnba-stat-spot
    runtime: docker
    repo: https://github.com/your-username/wnba-stat-spot.git
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: wnba-database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: wnba-database
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: wnba-database
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: wnba-database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: wnba-database
          property: password
      - key: CACHE_DRIVER
        value: redis
      - key: QUEUE_CONNECTION
        value: database
      - key: SESSION_DRIVER
        value: database

databases:
  - name: wnba-database
    databaseName: wnba_stat_spot
    user: wnba_user
