name: Ping Keep-Alive Endpoint

on:
  schedule:
    - cron: '*/12 * * * *'  # Runs every 15 minutes
  workflow_dispatch:        # Allows manual trigger from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Ping
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://wnba-stat-spot.onrender.com/